name: Terraform Apply

on:
  push:
    branches:
      - 'client/**'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    env:
      EXECUTION_ID: "467f656a-7938-42e0-8b93-95ecfdef9c30"
      IAM_ROLE: "arn:aws:iam::640168428612:role/SharedServicesCodePipelineCrossAccountRole"
      TF_BE_KEY: "client/640168428612.tfstate"
      TF_BE_WORKSPACE: "production"
      AWS_REGION: ${{ vars.AWS_REGION }}
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      TF_AWS_PROVIDER_VERSION: ${{ vars.TF_AWS_PROVIDER_VERSION }}
      TF_BE_DYNAMO_DB_TABLE: ${{ vars.TF_BE_DYNAMO_DB_TABLE }}
      TF_BE_KMS_KEY_ID: ${{ vars.TF_BE_KMS_KEY_ID }}
      TF_BE_S3_BUCKET: ${{ vars.TF_BE_S3_BUCKET }}
      TF_IN_AUTOMATION: ${{ vars.TF_IN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
