name: Terraform Plan2

on:
  push:
    branches:
      - 'clients/**'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform_plan2:
    runs-on: ubuntu-latest
    env:
      IAM_ROLE: ""
      TF_BE_KEY: ""
      TF_BE_WORKSPACE: ""
      AWS_REGION: ${{ vars.AWS_REGION }}
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      TF_AWS_PROVIDER_VERSION: ${{ vars.TF_AWS_PROVIDER_VERSION }}
      TF_BE_DYNAMO_DB_TABLE: ${{ vars.TF_BE_DYNAMO_DB_TABLE }}
      TF_BE_KMS_KEY_ID: ${{ vars.TF_BE_KMS_KEY_ID }}
      TF_BE_S3_BUCKET: ${{ vars.TF_BE_S3_BUCKET }}
      TF_IN_AUTOMATION: ${{ vars.TF_IN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
